---
- hosts: web
  tasks: 
    - name: "shut down CentOS 6 systems"
      touch: /var/verizon.txt
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "7.5"

