- hosts: web
  sudo: yes

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "CentOS"

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started
	
  handlers:
  - include_tasks: pro6.yaml
